type Conference @model {
  id: ID!
  name: String!
  location: String
  year: Int!
  startDate: String
  endDate: String
  url: String
  mainTag: String
  talks: [ConferenceTalk!]!
}

type ConferenceTalk {
  talkId: ID!
  title: String!
  abstract: String
  mainTag: String
  talkTime: String
  talkLength: Int
  tags: [String]
}

type Talk @model {
  id: ID!
  title: String!
  mainTag: String
}
